### ISSUE TITLE
set up our Kanban board

### ISSUE THREAD

**Issue by aliabbani** [aliabbani/Recipe-group-#9]
This is the link to our repository:
https://github.com/aliabbani/Recipe-group- 

This is the link of our Kanban board:
https://github.com/aliabbani/Recipe-group-/projects/2

We are a group of 2 students: 
Student A: Ali Abbani
Student B: Abdul Wuyep

**Comment by uwadonat** [comment]
Hi **@Team,** 

Your project is complete! you can move on to the next Milestone!
![approved](https://user-images.githubusercontent.com/65860678/152811733-49afccdb-f885-45ab-b522-6d853228164c.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
